services:
  pg_test:
    image: 'bitnami/postgresql'
    ports:
      - 5433:5432  # banco de teste
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=locadora_test
  pg_prod:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432  # banco de produção
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=locadora_prod
